version: '3.2'

services:
  # spotify-kafka:
  #   image: 'spotify/kafka'
  #   container_name: 'spotify-kafka'
  #   ports:
  #     - '2181:2181'
  #     - '9092:9092'
  #   environment:
  #     - ADVERTISED_HOST=localhost
  #     - ADVERTISED_PORT=9092

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  zookeeper:
    image: zookeeper
    ports:
      - '2181:2181'
    volumes:
      - ./zk-kafka/zookeeper/data:/data
      - ./zk-kafka/zookeeper/datalog:/datalog

  kafka:
      build: .
      ports:
        # - '2181:2181'
        - '9092:9092'
        - '9999:9999'
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:19092,OUTSIDE://${DOCKER_HOST_IP:-127.0.0.1}:9092
        KAFKA_LISTENERS: INSIDE://:19092,OUTSIDE://:9092
        KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_LOG4J_LOGGERS: kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
        KAFKA_OPTS: -javaagent:/usr/app/jmx_prometheus_javaagent.jar=7071:/usr/app/prom-jmx-agent-config.yml

        JMX_PORT: 9999
        KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
        KAFKA_JMX_OPTS: -Djava.rmi.server.hostname=127.0.0.1
          -Dcom.sun.management.jmxremote=true
          -Dcom.sun.management.jmxremote.local.only=false
          -Dcom.sun.management.jmxremote.rmi.port=9999
          -Dcom.sun.management.jmxremote.port=9999
          -Dcom.sun.management.jmxremote.authenticate=false
          -Dcom.sun.management.jmxremote.ssl=false

      volumes:
        - ./zk-kafka/kafka/data:/var/lib/kafka/data
      depends_on:
        - zookeeper
#
# Use the below to orchestrate Kafka, Zookeeper, kafka-simulate and KafkaMirror
# version: '3.0'

# # networks:
# #   kafka-net:
# #     driver: bridge
# #     ipam:
# #       driver: default
# #       config:
# #         - subnet: 172.16.0.0/24

# services:
#   spotify-kafka:
#     image: 'spotify/kafka'
#     container_name: 'spotify-kafka'
#     ports:
#       - '2181:2181'
#       - '9092:9092'
#     environment:
#       # - ADVERTISED_HOST=172.16.0.12
#       - ADVERTISED_HOST=localhost
#       - ADVERTISED_PORT=9092
# networks:
#   kafka-net:
#     ipv4_address: 172.16.0.12

# kafka-simulator:
#   image: 'kafkamirror/kafka-simulator'
#   container_name: 'kafka-simulator'
#   networks:
#     kafka-net:
#       ipv4_address: 172.16.0.14
#   ports:
#     - '3001:3001'
#     - '3030:3030'
#   depends_on:
#     - spotify-kafka

# kafkamirror:
#   image: 'kafkamirror/kafkamirror'
#   container_name: 'kafkamirror'
#   ports:
#     - '3000:3000'
#     - '8080:8080'
#   depends_on:
#     - kafka-simulator
#   networks:
#     kafka-net:
#       ipv4_address: 172.16.0.13
